apiVersion: v1
kind: Service
metadata:
  name: clickhouse-openreplay-clickhouse
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
      name: web
      {{- if .Values.service.webNodePort }}
      nodePort: {{ .Values.service.webNodePort }}
      {{- end }}
    - port: {{ .Values.service.dataPort }}
      targetPort: data
      protocol: TCP
      name: data
      {{- if .Values.service.dataNodePort }}
      nodePort: {{ .Values.service.dataNodePort }}
      {{- end }}
    - port: 7171
      targetPort: backup-web
      protocol: TCP
      name: backup-web
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
