version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8.2.7-alpine
    container_name: mida-clickhouse
    hostname: clickhouse
    restart: unless-stopped
    ports:
      - "30900:8123"    # HTTP interface (web UI)
      - "30123:9000"    # Native TCP interface
      - "7171:7171"     # Backup API
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: root
      CLICKHOUSE_PASSWORD: hoangnx1
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse-config:/etc/clickhouse-server/config.d
      - ./clickhouse-users:/etc/clickhouse-server/users.d
    networks:
      - mida-storage
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  clickhouse-backup:
    image: alexakulov/clickhouse-backup:latest
    container_name: mida-clickhouse-backup
    restart: unless-stopped
    ports:
      - "7171:7171"
    environment:
      API_LISTEN: "0.0.0.0:7171"
      BACKUPS_TO_KEEP_LOCAL: "1"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_USERNAME: "root"
      CLICKHOUSE_PASSWORD: "hoangnx1"
      # Uncomment and configure for S3 backup
      # REMOTE_STORAGE: "s3"
      # S3_ACCESS_KEY: "your-access-key"
      # S3_SECRET_KEY: "your-secret-key"
      # S3_ENDPOINT: "http://minio:9000"
      # S3_BUCKET: "clickhouse-backups"
      # S3_PATH: "backup"
      # S3_FORCE_PATH_STYLE: "true"
      # S3_DISABLE_SSL: "true"
    volumes:
      - clickhouse_backup:/backup
    networks:
      - mida-storage
    depends_on:
      clickhouse:
        condition: service_healthy

  minio:
    image: bitnami/minio:2023.2.10-debian-11-r1
    container_name: mida-minio
    hostname: minio
    restart: unless-stopped
    ports:
      - "30000:9001"    # MinIO Console (Web UI)
      - "9000:9000"     # MinIO API
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-secret-key-2024
      MINIO_DEFAULT_BUCKETS: midareplay-storage
      MINIO_BROWSER: "on"
      BITNAMI_DEBUG: "false"
      MINIO_FORCE_NEW_KEYS: "no"
    volumes:
      - minio_data:/data
    networks:
      - mida-storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: >
      sh -c "
      mkdir -p /data/midareplay-storage &&
      minio server /data --console-address ':9001'
      "

volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
  clickhouse_backup:
    driver: local
  minio_data:
    driver: local

networks:
  mida-storage:
    driver: bridge
    name: mida-storage
